name: Deploy to Development

on:
  push:
    branches: [ development ]  # Sesuaikan dengan branch development Anda

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'  # Sesuaikan dengan versi PHP di Hostinger
        
    - name: Install Dependencies
      run: composer install --no-dev --optimize-autoloader
      
    - name: Compile Assets
      run: |
        npm install
        npm run build
        
    - name: Deploy to Hostinger
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /public_html/dev/  # Sesuaikan dengan path subdomain Anda
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
          .env.example
          docker-compose.yml
